trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type:       github
      ref:        main
      endpoint:   ni (2)
      name:       ni/niveristand-custom-device-build-tools

stages:
  - template: azure-templates/stages.yml
    parameters:

      lvVersionsToBuild:
        - version: '2020'
          bitness: '32bit'
        - version: '2021'
          bitness: '64bit'
        - version: '2023'
          bitness: '64bit'

      codegenVis:
        - 'Source\Script FXP Read.vi'
        - 'Source\Script FXP Write.vi'

      buildSteps:
        - projectLocation: 'Source\FXP LLB.lvproj'
          buildOperation: 'ExecuteBuildSpecAllTargets'
          target: 'All'
          buildSpec: 'FXP LLB'

      releaseVersion: '23.0.0'
      quarterlyReleaseVersion: '2023 Q1'
      buildOutputLocation: 'Built'
      archiveLocation: '\\nirvana\Measurements\VeriStandAddons\prototype\scan_engine_fxp'
      pack: false
